pipeline {
    agent any

    tools {
        maven 'Maven 3.9.7'
        jdk 'OpenJDK 22'
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
    }
}
